version: '3'

tasks:
  update:
    aliases: [u]
    desc: Update flake inputs
    cmds:
      - nix flake update

  rebuild-switch:
    aliases: [rb-s]
    desc: Rebuild NixOS and switch immediatly
    cmds:
      - sudo nixos-rebuild switch
      - task: commit-after-rebuilt

  rebuild-boot:
    aliases: [rb-b]
    desc: Rebuild NixOS and enable on next reboot 
    cmds:
      - sudo nixos-rebuild boot
      - task: commit-after-rebuilt

  flake-check:
    aliases: [ check fc]
    desc: Check if the flake can compile
    cmds:
      - nix flake check

  rebuild-*:
    desc: Custom Rebuild
    vars:
      ARG: '{{index .MATCH 0}}'
    cmds:
      - sudo nixos-rebuild {{.ARG}}

  garbage-collect:
    aliases: [gc]
    desc: Run nix Garbage collector
    cmds:
      - sudo nix-collect-garbage -d
      - sudo /run/current-system/bin/switch-to-configuration boot

  branches-gc:
    aliases: [b-gc]
    desc: Cleanup old rebuid branches
    cmds:
      - ./scripts/cleanup.sh {{.CLI_ARGS}}

  commit-after-rebuilt:
    internal: true
    preconditions:
      - sh: 'test "$(git rev-parse --abbrev-ref HEAD)" = "master"'
        msg: "Not on master branch, skipping commit"
    cmds:
      - ./scripts/commit-routine.sh
    silent: true
