[[language]]
name = "nix"
language-servers = [ "nixd", "nil" ]

[language-server.nixd.config.nixd]
nixpkgs = { expr = "import (builtins.getFlake (builtins.toString ./.)).inputs.nixpkgs {}" }

[language-server.nixd.config.formatting]
command = [ "nixfmt" ]

[language-server.nixd.config.nixd.options]
nixos = { expr = "(builtins.getFlake (builtins.toString ./.)).nixosConfigurations.Xavers-nixDesktop.options" }
home-manager = { expr = "(builtins.getFlake (builtins.toString ./.)).nixosConfigurations.Xavers-nixDesktop.options.home-manager.users.type.getSubOptions []" }
